-- ============================================================
-- PRY2204 - SEMANA 8 - ACTIVIDAD SUMATIVA
-- Taller Mecánico Mikes Ltda.
-- Alumno: Alejandro Serrano
-- Fecha: 29/09/2026
-- ============================================================

ALTER SESSION SET CURRENT_SCHEMA = PRY2204_S8;

-- ============================================================
-- CASO 1: CREACIÓN DE TABLAS
-- ============================================================

-- PAIS
CREATE TABLE pais (
    id_pais      NUMBER(3) GENERATED BY DEFAULT AS IDENTITY 
                 (START WITH 9 INCREMENT BY 3) NOT NULL,
    nom_pais     VARCHAR2(30) NOT NULL,
    CONSTRAINT pais_pk PRIMARY KEY (id_pais)
);

-- SERVICIO
CREATE TABLE servicio (
    id_servicio  NUMBER(3) NOT NULL,
    descripcion  VARCHAR2(100) NOT NULL,
    costo        NUMBER(10) NOT NULL,
    CONSTRAINT servicio_pk PRIMARY KEY (id_servicio)
);

-- MARCA
CREATE TABLE marca (
    id_marca   NUMBER(2) NOT NULL,
    des_marca  VARCHAR2(30) NOT NULL,
    CONSTRAINT marca_pk PRIMARY KEY (id_marca)
);

-- TIPO_AUTOMOVIL
CREATE TABLE tipo_automovil (
    id_tipoauto  VARCHAR2(3) NOT NULL,
    nom_tipoauto VARCHAR2(30) NOT NULL,
    CONSTRAINT tipo_automovil_pk PRIMARY KEY (id_tipoauto)
);

-- MECANICO
CREATE TABLE mecanico (
    cod_mecanico     NUMBER(4) GENERATED BY DEFAULT AS IDENTITY 
                     (START WITH 460 INCREMENT BY 7) NOT NULL,
    pnombre          VARCHAR2(25) NOT NULL,
    snombre          VARCHAR2(25),
    apaterno         VARCHAR2(25) NOT NULL,
    amaterno         VARCHAR2(25),
    bono_jefatura    NUMBER(10),
    sueldo           NUMBER(10) NOT NULL,
    monto_impuestos  NUMBER(10),
    cod_supervisor   NUMBER(4),
    CONSTRAINT mecanico_pk PRIMARY KEY (cod_mecanico),
    CONSTRAINT mecanico_supervisor_fk FOREIGN KEY (cod_supervisor) 
        REFERENCES mecanico(cod_mecanico)
);

-- CIUDAD
CREATE TABLE ciudad (
    id_ciudad  NUMBER(4) NOT NULL,
    nom_ciudad VARCHAR2(30) NOT NULL,
    cod_pais   NUMBER(3) NOT NULL,
    CONSTRAINT ciudad_pk PRIMARY KEY (id_ciudad),
    CONSTRAINT ciudad_pais_fk FOREIGN KEY (cod_pais) REFERENCES pais(id_pais)
);

-- SUCURSAL
CREATE TABLE sucursal (
    id_sucursal  VARCHAR2(3) NOT NULL,
    nom_sucursal VARCHAR2(30) NOT NULL,
    calle        VARCHAR2(50) NOT NULL,
    num_calle    NUMBER(5) NOT NULL,
    cod_ciudad   NUMBER(4) NOT NULL,
    CONSTRAINT sucursal_pk PRIMARY KEY (id_sucursal),
    CONSTRAINT sucursal_ciudad_fk FOREIGN KEY (cod_ciudad) REFERENCES ciudad(id_ciudad)
);

-- MODELO
CREATE TABLE modelo (
    id_modelo    NUMBER(3) NOT NULL,
    nom_modelo   VARCHAR2(30) NOT NULL,
    descripcion  VARCHAR2(60),
    id_marca     NUMBER(2) NOT NULL,
    id_tipoauto  VARCHAR2(3) NOT NULL,
    CONSTRAINT modelo_pk PRIMARY KEY (id_modelo),
    CONSTRAINT modelo_marca_fk FOREIGN KEY (id_marca) REFERENCES marca(id_marca),
    CONSTRAINT modelo_tipoauto_fk FOREIGN KEY (id_tipoauto) REFERENCES tipo_automovil(id_tipoauto)
);

-- CLIENTE
CREATE TABLE cliente (
    rut         NUMBER(8) NOT NULL,
    dv          CHAR(1) NOT NULL,
    pnombre     VARCHAR2(25) NOT NULL,
    snombre     VARCHAR2(25),
    apaterno    VARCHAR2(25) NOT NULL,
    amaterno    VARCHAR2(25),
    email       VARCHAR2(100),
    direccion   VARCHAR2(50),
    telefono    VARCHAR2(15),
    cod_ciudad  NUMBER(4) NOT NULL,
    tipo_cli    VARCHAR2(10) NOT NULL,
    CONSTRAINT cliente_pk PRIMARY KEY (rut),
    CONSTRAINT cliente_ciudad_fk FOREIGN KEY (cod_ciudad) REFERENCES ciudad(id_ciudad)
);

-- AUTOMOVIL
CREATE TABLE automovil (
    patente     VARCHAR2(6) NOT NULL,
    anio        NUMBER(4) NOT NULL,
    color       VARCHAR2(20),
    nro_motor   VARCHAR2(20),
    nro_chasis  VARCHAR2(20),
    rut         NUMBER(8) NOT NULL,
    id_modelo   NUMBER(3) NOT NULL,
    CONSTRAINT automovil_pk PRIMARY KEY (patente),
    CONSTRAINT automovil_cliente_fk FOREIGN KEY (rut) REFERENCES cliente(rut),
    CONSTRAINT automovil_modelo_fk FOREIGN KEY (id_modelo) REFERENCES modelo(id_modelo)
);

-- MANTENCION
CREATE TABLE mantencion (
    nro_mantencion  NUMBER(4) NOT NULL,
    id_sucursal     VARCHAR2(3) NOT NULL,
    fecha_llegada   DATE,
    fecha_entrega   DATE,
    rut             NUMBER(8) NOT NULL,
    cod_mecanico    NUMBER(4) NOT NULL,
    estado          VARCHAR2(15) NOT NULL,
    CONSTRAINT mantencion_pk PRIMARY KEY (nro_mantencion, id_sucursal),
    CONSTRAINT mantencion_sucursal_fk FOREIGN KEY (id_sucursal) REFERENCES sucursal(id_sucursal),
    CONSTRAINT mantencion_cliente_fk FOREIGN KEY (rut) REFERENCES cliente(rut),
    CONSTRAINT mantencion_mecanico_fk FOREIGN KEY (cod_mecanico) REFERENCES mecanico(cod_mecanico)
);

-- DETALLE_SERVICIO
CREATE TABLE detalle_servicio (
    nro_mantencion  NUMBER(4) NOT NULL,
    id_sucursal     VARCHAR2(3) NOT NULL,
    id_servicio     NUMBER(3) NOT NULL,
    CONSTRAINT detalle_servicio_pk PRIMARY KEY (nro_mantencion, id_sucursal, id_servicio),
    CONSTRAINT detalle_mantencion_fk FOREIGN KEY (nro_mantencion, id_sucursal) 
        REFERENCES mantencion(nro_mantencion, id_sucursal),
    CONSTRAINT detalle_servicio_fk FOREIGN KEY (id_servicio) REFERENCES servicio(id_servicio)
);

-- ESTANDAR
CREATE TABLE estandar (
    rut        NUMBER(8) NOT NULL,
    porc_desc  NUMBER(4,2) NOT NULL,
    CONSTRAINT estandar_pk PRIMARY KEY (rut),
    CONSTRAINT estandar_cliente_fk FOREIGN KEY (rut) REFERENCES cliente(rut)
);

-- PREMIUM
CREATE TABLE premium (
    rut           NUMBER(8) NOT NULL,
    porc_desc     NUMBER(4,2) NOT NULL,
    monto_credito NUMBER(10) NOT NULL,
    CONSTRAINT premium_pk PRIMARY KEY (rut),
    CONSTRAINT premium_cliente_fk FOREIGN KEY (rut) REFERENCES cliente(rut)
);

-- ============================================================
-- CASO 2: ALTER TABLE (Reglas de negocio)
-- ============================================================

-- Regla 1: costo_total ya fue omitido en la creación

-- Regla 2 y 3: PK compuesta y FK ya aplicadas en Caso 1

-- Regla 4: Email único en CLIENTE
ALTER TABLE cliente ADD CONSTRAINT cliente_email_un UNIQUE (email);

-- Regla 5: DV del RUT
ALTER TABLE cliente ADD CONSTRAINT cliente_dv_ck 
CHECK (dv IN ('0','1','2','3','4','5','6','7','8','9','K'));

-- Regla 6: Sueldo mínimo mecánico
ALTER TABLE mecanico ADD CONSTRAINT mecanico_sueldo_ck 
CHECK (sueldo >= 510000);

-- Regla 7: Estados válidos de mantención
ALTER TABLE mantencion ADD CONSTRAINT mantencion_estado_ck 
CHECK (estado IN ('Reserva','Ingresado','Entregado','Anulado'));

-- ============================================================
-- CASO 3: POBLAMIENTO
-- ============================================================

-- PAIS
INSERT INTO pais (nom_pais) VALUES ('Chile');
INSERT INTO pais (nom_pais) VALUES ('Peru');
INSERT INTO pais (nom_pais) VALUES ('Colombia');

-- SERVICIO
CREATE SEQUENCE seq_servicio START WITH 400 INCREMENT BY 2 NOCACHE;
INSERT INTO servicio VALUES (seq_servicio.NEXTVAL, 'Cambio Luces', 45000);
INSERT INTO servicio VALUES (seq_servicio.NEXTVAL, 'Desabolladura', 67000);
INSERT INTO servicio VALUES (seq_servicio.NEXTVAL, 'Revision Frenos', 30000);
INSERT INTO servicio VALUES (seq_servicio.NEXTVAL, 'Cambio Puerta Trasera', 50000);

-- CIUDAD
CREATE SEQUENCE seq_ciudad START WITH 165 INCREMENT BY 5 NOCACHE;
INSERT INTO ciudad VALUES (seq_ciudad.NEXTVAL, 'Santiago', 9);
INSERT INTO ciudad VALUES (seq_ciudad.NEXTVAL, 'Lima', 12);
INSERT INTO ciudad VALUES (seq_ciudad.NEXTVAL, 'Bogotá', 15);

-- SUCURSAL
INSERT INTO sucursal VALUES ('S01', 'Providencia', 'Av. A. Varas', 234, 165);
INSERT INTO sucursal VALUES ('S02', 'Las 4 esquinas', 'Av. Latina', 669, 170);
INSERT INTO sucursal VALUES ('S03', 'El Cafetero', 'Av. El Faro', 900, 175);

-- MECANICO
INSERT INTO mecanico (pnombre, snombre, apaterno, amaterno, bono_jefatura, sueldo, monto_impuestos, cod_supervisor)
VALUES ('Jorge', 'Pablo', 'Soto', 'Sierpe', 540000, 2759000, 223580, NULL);
INSERT INTO mecanico (pnombre, snombre, apaterno, amaterno, bono_jefatura, sueldo, monto_impuestos, cod_supervisor)
VALUES ('Pedro', 'Jose', 'Manriquez', 'Corral', NULL, 759000, 23980, NULL);
INSERT INTO mecanico (pnombre, snombre, apaterno, amaterno, bono_jefatura, sueldo, monto_impuestos, cod_supervisor)
VALUES ('Sandra', 'Josefa', 'Letelier', 'S.', 350000, 659000, 22358, 460);
INSERT INTO mecanico (pnombre, snombre, apaterno, amaterno, bono_jefatura, sueldo, monto_impuestos, cod_supervisor)
VALUES ('Felipe', 'M.', 'Vidal', 'A.', NULL, 759000, 23580, 460);
INSERT INTO mecanico (pnombre, snombre, apaterno, amaterno, bono_jefatura, sueldo, monto_impuestos, cod_supervisor)
VALUES ('Jose', 'Miguel', 'Troncoso', 'B.', NULL, 659000, 44580, 474);
INSERT INTO mecanico (pnombre, snombre, apaterno, amaterno, bono_jefatura, sueldo, monto_impuestos, cod_supervisor)
VALUES ('Juan', 'Pablo', 'Sánchez', 'R.', NULL, 859000, 23380, 474);
INSERT INTO mecanico (pnombre, snombre, apaterno, amaterno, bono_jefatura, sueldo, monto_impuestos, cod_supervisor)
VALUES ('Carlos', 'Felipe', 'Soto', 'J.', 350000, 597000, 23580, 474);
INSERT INTO mecanico (pnombre, snombre, apaterno, amaterno, bono_jefatura, sueldo, monto_impuestos, cod_supervisor)
VALUES ('Alberto', 'P.', 'Cerda', 'Ramirez', NULL, 559000, 22380, 460);
INSERT INTO mecanico (pnombre, snombre, apaterno, amaterno, bono_jefatura, sueldo, monto_impuestos, cod_supervisor)
VALUES ('Alejandra', 'Gabriela', 'Infanti', 'R.', NULL, 659000, 22380, 460);
INSERT INTO mecanico (pnombre, snombre, apaterno, amaterno, bono_jefatura, sueldo, monto_impuestos, cod_supervisor)
VALUES ('Roberto', 'Patricio', 'Gutierrez', 'Sosa', NULL, 859000, 22380, 460);

COMMIT;

-- ============================================================
-- CASO 4: INFORMES
-- ============================================================

-- INFORME 1: Simulación de rebaja de impuestos
SELECT 
    cod_mecanico                            AS "ID MECANICO",
    pnombre || ' ' || apaterno              AS "NOMBRE MECANICO",
    sueldo                                  AS "SALARIO",
    monto_impuestos                         AS "IMPUESTO ACTUAL",
    ROUND(monto_impuestos * 0.8)            AS "IMPUESTO REBAJADO",
    ROUND(sueldo - (monto_impuestos * 0.8)) AS "SUELDO CON REBAJA IMPUESTOS"
FROM mecanico
WHERE bono_jefatura IS NULL
  AND monto_impuestos < 40000
ORDER BY "IMPUESTO ACTUAL" DESC, apaterno ASC;

-- INFORME 2: Ajuste salarial del 5%
SELECT 
    cod_mecanico                                    AS "IDENTIFICADOR",
    pnombre || ' ' || snombre || ' ' || apaterno    AS "MECANICO",
    sueldo                                          AS "SALARIO ACTUAL",
    ROUND(sueldo * 0.05)                            AS "AJUSTE",
    ROUND(sueldo * 1.05)                            AS "SUELDO_REAJUSTADO"
FROM mecanico
WHERE (sueldo BETWEEN 600000 AND 900000) 
   OR cod_supervisor IS NULL
ORDER BY "SALARIO ACTUAL" ASC, "MECANICO" DESC;